version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    image: cherryp0p/server:latest
    container_name: server-container
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: todo_db
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  client:
    image: cherryp0p/client:latest
    container_name: client-container
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mysql_data:
